##############################################################
# Mobile Application Programming (SCSJ3623)
# Semester 2, 2019/2020
##############################################################

# REST API Server on Local Firebase
# @baseUrl = http://localhost:5001/smartmathturtledevs/us-central1/api

# REST API Server on Live Firebase
# @baseUrl = https://us-central1-jumail-backend-firebase-rest.cloudfunctions.net/api
@baseUrl = https://us-central1-smartmathturtledevs.cloudfunctions.net/api

### Getting the list of user
GET {{baseUrl}}/user

###  Getting a user of given id
GET {{baseUrl}}/user/ToS1eqpANIX8vYHrUc2V

###  Create a new user
POST {{baseUrl}}/user
Content-Type: application/json

{
    "name": "Amir",
    "login" : "amir@gmail.com",
    "password":"amir1234"
}

### Update the status of a given user (whether is completed or not)
PATCH {{baseUrl}}/user/HXHpok2n641QmTJEvREm
Content-Type: application/json

{
    "completed":true
}


### Replace the entire fields of a given user
PUT {{baseUrl}}/user/H7kv4nPyQKXodwAui0qu
Content-Type: application/json

{
    "completed": true
}

### Deleting a given user
DELETE {{baseUrl}}/user/VjeS8LtZAuhYPTKORVh4
